<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:30.
 */
class AdminControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AdminController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AdminController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AdminController::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminController::panel
     * @todo   Implement testPanel().
     */
    public function testPanel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminController::editAccounts
     * @todo   Implement testEditAccounts().
     */
    public function testEditAccounts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminController::editDropDowns
     * @todo   Implement testEditDropDowns().
     */
    public function testEditDropDowns() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminController::editPageTimeouts
     * @todo   Implement testEditPageTimeouts().
     */
    public function testEditPageTimeouts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminController::uploadSchedule
     * @todo   Implement testUploadSchedule().
     */
    public function testUploadSchedule() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminController::dataDump
     * @todo   Implement testDataDump().
     */
    public function testDataDump() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminController::reqDataDump
     * @todo   Implement testReqDataDump().
     */
    public function testReqDataDump() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminController::actionAccountSettings
     * @todo   Implement testActionAccountSettings().
     */
    public function testActionAccountSettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
