<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:32.
 */
class AuthTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Auth
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Auth;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Auth::checkAuthentication
     * @todo   Implement testCheckAuthentication().
     */
    public function testCheckAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auth::checkAdminAuthentication
     * @todo   Implement testCheckAdminAuthentication().
     */
    public function testCheckAdminAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auth::checkGreeterAuthentication
     * @todo   Implement testCheckGreeterAuthentication().
     */
    public function testCheckGreeterAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auth::checkTutorAuthentication
     * @todo   Implement testCheckTutorAuthentication().
     */
    public function testCheckTutorAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auth::checkStudentAuthentication
     * @todo   Implement testCheckStudentAuthentication().
     */
    public function testCheckStudentAuthentication() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Auth::checkSessionConcurrency
     * @todo   Implement testCheckSessionConcurrency().
     */
    public function testCheckSessionConcurrency() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
