<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:32.
 */
class MailTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Mail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Mail;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Mail::sendMailWithNativeMailFunction
     * @todo   Implement testSendMailWithNativeMailFunction().
     */
    public function testSendMailWithNativeMailFunction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mail::sendMailWithSwiftMailer
     * @todo   Implement testSendMailWithSwiftMailer().
     */
    public function testSendMailWithSwiftMailer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mail::sendMailWithPHPMailer
     * @todo   Implement testSendMailWithPHPMailer().
     */
    public function testSendMailWithPHPMailer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mail::sendMail
     * @todo   Implement testSendMail().
     */
    public function testSendMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mail::getError
     * @todo   Implement testGetError().
     */
    public function testGetError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
