<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:34.
 */
class ViewTest extends PHPUnit_Framework_TestCase {

    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
       // $this->object = new View;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers View::renderEx
     * @todo   Implement testRenderEx().
     */
    public function testRenderEx() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::renderMulti
     * @todo   Implement testRenderMulti().
     */
    public function testRenderMulti() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::renderWithoutHeaderAndFooter
     * @todo   Implement testRenderWithoutHeaderAndFooter().
     */
    public function testRenderWithoutHeaderAndFooter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::renderJSON
     * @todo   Implement testRenderJSON().
     */
    public function testRenderJSON() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::renderFeedbackMessages
     * @todo   Implement testRenderFeedbackMessages().
     */
    public function testRenderFeedbackMessages() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::checkForActiveController
     * @todo   Implement testCheckForActiveController().
     */
    public function testCheckForActiveController() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::checkForActiveAction
     * @todo   Implement testCheckForActiveAction().
     */
    public function testCheckForActiveAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers View::checkForActiveControllerAndAction
     * @todo   Implement testCheckForActiveControllerAndAction().
     */
    public function testCheckForActiveControllerAndAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
