<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:33.
 */
class ApplicationTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Application
     */
    protected $application;
    protected $controller;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
       // $this->application = new Application();
        
    }

    
	public function testTrueIsTrue()
	{
		// call for environment should return "development"
                $foo = true;
                $this->assertEquals($foo, true);
	}
    
       // public function test
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
