<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:33.
 */
class CsrfTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Csrf
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Csrf;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Csrf::isTokenValid
     * @todo   Implement testIsTokenValid().
     */
    public function testIsTokenValid() {
        $testValue = 'csrf_token';
        $_POST[$testValue] = 'hoorayValue';
        $_SESSION[$testValue] = 'hoorayValue';
        echo Csrf::isTokenValid();
        $this->assertEquals(true, Csrf::isTokenValid());
        
    }

}
