<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:34.
*/
class EncryptionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Encryption
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Encryption::encrypt and decrypt, must be coupled
     */
    public function testEncrypt() {
        $testEncryptMe = 'potato';
        $this->assertEquals(Encryption::decrypt(Encryption::encrypt($testEncryptMe)), $testEncryptMe);

    }

}
