<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:31.
 */
class ErrorControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ErrorController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new ErrorController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ErrorController::error404
     * @todo   Implement testError404().
     */
    public function testError404() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
