<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:32.
 */
class GreeterControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var GreeterController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GreeterController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GreeterController::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GreeterController::updateTable
     * @todo   Implement testUpdateTable().
     */
    public function testUpdateTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GreeterController::updateTable2
     * @todo   Implement testUpdateTable2().
     */
    public function testUpdateTable2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GreeterController::editView
     * @todo   Implement testEditView().
     */
    public function testEditView() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GreeterController::editViewSaver
     * @todo   Implement testEditViewSaver().
     */
    public function testEditViewSaver() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GreeterController::actionAccountSettings
     * @todo   Implement testActionAccountSettings().
     */
    public function testActionAccountSettings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GreeterController::removeSpecificTable
     * @todo   Implement testRemoveSpecificTable().
     */
    public function testRemoveSpecificTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
