<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:31.
 */
class LoginControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LoginController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoginController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers LoginController::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::logout
     * @todo   Implement testLogout().
     */
    public function testLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::loginWithCookie
     * @todo   Implement testLoginWithCookie().
     */
    public function testLoginWithCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::showProfile
     * @todo   Implement testShowProfile().
     */
    public function testShowProfile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::editUsername
     * @todo   Implement testEditUsername().
     */
    public function testEditUsername() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::editUsername_action
     * @todo   Implement testEditUsername_action().
     */
    public function testEditUsername_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::editUserEmail
     * @todo   Implement testEditUserEmail().
     */
    public function testEditUserEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::editUserEmail_action
     * @todo   Implement testEditUserEmail_action().
     */
    public function testEditUserEmail_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::changeUserRole
     * @todo   Implement testChangeUserRole().
     */
    public function testChangeUserRole() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::changeUserRole_action
     * @todo   Implement testChangeUserRole_action().
     */
    public function testChangeUserRole_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::register
     * @todo   Implement testRegister().
     */
    public function testRegister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::register_action
     * @todo   Implement testRegister_action().
     */
    public function testRegister_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::verify
     * @todo   Implement testVerify().
     */
    public function testVerify() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::requestPasswordReset
     * @todo   Implement testRequestPasswordReset().
     */
    public function testRequestPasswordReset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::requestPasswordReset_action
     * @todo   Implement testRequestPasswordReset_action().
     */
    public function testRequestPasswordReset_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::verifyPasswordReset
     * @todo   Implement testVerifyPasswordReset().
     */
    public function testVerifyPasswordReset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::setNewPassword
     * @todo   Implement testSetNewPassword().
     */
    public function testSetNewPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::changePassword
     * @todo   Implement testChangePassword().
     */
    public function testChangePassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginController::changePassword_action
     * @todo   Implement testChangePassword_action().
     */
    public function testChangePassword_action() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
