<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:31.
 */
class TutorControllerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TutorController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TutorController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TutorController::index
     * @todo   Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TutorController::helpPanel
     * @todo   Implement testHelpPanel().
     */
    public function testHelpPanel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TutorController::leaveHelpPanel
     * @todo   Implement testLeaveHelpPanel().
     */
    public function testLeaveHelpPanel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TutorController::updateTableTutors
     * @todo   Implement testUpdateTableTutors().
     */
    public function testUpdateTableTutors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
