<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:11.
 */
//require 'AdminModel.php';
//require Config::get('PATH_CONTROLLER') . 'AdminModel' . '.php';
//require '/var/www/html/TutorQueue/Application/Controller/AdminModel.php';
class AdminModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AdminModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AdminModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AdminModel::setAccountDeletionStatus
     * @todo   Implement testSetAccountDeletionStatus().
     */
    public function testSetAccountDeletionStatus() {
        // Remove the following lines when you implement this test.
        $variable = true;
        $this->assertTrue($variable, true);
    }

    /**
     * @covers AdminModel::reqDataDump
     * @todo   Implement testReqDataDump().
     */
    public function testReqDataDump() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AdminModel::getQuickNotes
     * @todo   Implement testGetQuickNotes().
     */
    public function testGetQuickNotes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
