<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:13.
 */
class GreeterModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var GreeterModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new GreeterModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers GreeterModel::editViewSaver
     * @todo   Implement testEditViewSaver().
     */
    public function testEditViewSaver() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GreeterModel::setRequestDetails
     * @todo   Implement testSetRequestDetails().
     */
    public function testSetRequestDetails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers GreeterModel::removeSpecificTable
     * @todo   Implement testRemoveSpecificTable().
     */
    public function testRemoveSpecificTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
