<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:12.
 */
class LoginModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LoginModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoginModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers LoginModel::login
     * @todo   Implement testLogin().
     */
    public function testLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::loginWithCookie
     * @todo   Implement testLoginWithCookie().
     */
    public function testLoginWithCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::logout
     * @todo   Implement testLogout().
     */
    public function testLogout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::setSuccessfulLoginIntoSession
     * @todo   Implement testSetSuccessfulLoginIntoSession().
     */
    public function testSetSuccessfulLoginIntoSession() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::incrementFailedLoginCounterOfUser
     * @todo   Implement testIncrementFailedLoginCounterOfUser().
     */
    public function testIncrementFailedLoginCounterOfUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::resetFailedLoginCounterOfUser
     * @todo   Implement testResetFailedLoginCounterOfUser().
     */
    public function testResetFailedLoginCounterOfUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::saveTimestampOfLoginOfUser
     * @todo   Implement testSaveTimestampOfLoginOfUser().
     */
    public function testSaveTimestampOfLoginOfUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::setRememberMeInDatabaseAndCookie
     * @todo   Implement testSetRememberMeInDatabaseAndCookie().
     */
    public function testSetRememberMeInDatabaseAndCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::deleteCookie
     * @todo   Implement testDeleteCookie().
     */
    public function testDeleteCookie() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LoginModel::isUserLoggedIn
     * @todo   Implement testIsUserLoggedIn().
     */
    public function testIsUserLoggedIn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
