<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:12.
 */
class PasswordResetModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PasswordResetModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PasswordResetModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PasswordResetModel::requestPasswordReset
     * @todo   Implement testRequestPasswordReset().
     */
    public function testRequestPasswordReset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::setPasswordResetDatabaseToken
     * @todo   Implement testSetPasswordResetDatabaseToken().
     */
    public function testSetPasswordResetDatabaseToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::sendPasswordResetMail
     * @todo   Implement testSendPasswordResetMail().
     */
    public function testSendPasswordResetMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::verifyPasswordReset
     * @todo   Implement testVerifyPasswordReset().
     */
    public function testVerifyPasswordReset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::saveNewUserPassword
     * @todo   Implement testSaveNewUserPassword().
     */
    public function testSaveNewUserPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::setNewPassword
     * @todo   Implement testSetNewPassword().
     */
    public function testSetNewPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::validateResetPassword
     * @todo   Implement testValidateResetPassword().
     */
    public function testValidateResetPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::saveChangedPassword
     * @todo   Implement testSaveChangedPassword().
     */
    public function testSaveChangedPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::changePassword
     * @todo   Implement testChangePassword().
     */
    public function testChangePassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PasswordResetModel::validatePasswordChange
     * @todo   Implement testValidatePasswordChange().
     */
    public function testValidatePasswordChange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
