<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:11.
 */
class RegistrationModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RegistrationModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new RegistrationModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers RegistrationModel::registerNewUser
     * @todo   Implement testRegisterNewUser().
     */
    public function testRegisterNewUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistrationModel::registrationInputValidation
     * @todo   Implement testRegistrationInputValidation().
     */
    public function testRegistrationInputValidation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistrationModel::validateUserName
     * @todo   Implement testValidateUserName().
     */
    public function testValidateUserName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistrationModel::validateUserEmail
     * @todo   Implement testValidateUserEmail().
     */
    public function testValidateUserEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistrationModel::validateUserPassword
     * @todo   Implement testValidateUserPassword().
     */
    public function testValidateUserPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistrationModel::writeNewUserToDatabase
     * @todo   Implement testWriteNewUserToDatabase().
     */
    public function testWriteNewUserToDatabase() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistrationModel::rollbackRegistrationByUserId
     * @todo   Implement testRollbackRegistrationByUserId().
     */
    public function testRollbackRegistrationByUserId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistrationModel::sendVerificationEmail
     * @todo   Implement testSendVerificationEmail().
     */
    public function testSendVerificationEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers RegistrationModel::verifyNewUser
     * @todo   Implement testVerifyNewUser().
     */
    public function testVerifyNewUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
