<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:13.
 */
class TutorModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TutorModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TutorModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TutorModel::setHelpRequestTransitionState
     * @todo   Implement testSetHelpRequestTransitionState().
     */
    public function testSetHelpRequestTransitionState() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TutorModel::appendNotesHelpRequest
     * @todo   Implement testAppendNotesHelpRequest().
     */
    public function testAppendNotesHelpRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TutorModel::confirmTutorCode
     * @todo   Implement testConfirmTutorCode().
     */
    public function testConfirmTutorCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TutorModel::logoutTimeoutTutor
     * @todo   Implement testLogoutTimeoutTutor().
     */
    public function testLogoutTimeoutTutor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
