<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-30 at 23:05:12.
 */
class UserModelTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UserModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UserModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UserModel::getPublicProfilesOfAllUsers
     * @todo   Implement testGetPublicProfilesOfAllUsers().
     */
    public function testGetPublicProfilesOfAllUsers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::getPublicProfileOfUser
     * @todo   Implement testGetPublicProfileOfUser().
     */
    public function testGetPublicProfileOfUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::getUserDataByUserNameOrEmail
     * @todo   Implement testGetUserDataByUserNameOrEmail().
     */
    public function testGetUserDataByUserNameOrEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::doesUsernameAlreadyExist
     * @todo   Implement testDoesUsernameAlreadyExist().
     */
    public function testDoesUsernameAlreadyExist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::doesEmailAlreadyExist
     * @todo   Implement testDoesEmailAlreadyExist().
     */
    public function testDoesEmailAlreadyExist() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::saveNewUserName
     * @todo   Implement testSaveNewUserName().
     */
    public function testSaveNewUserName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::saveNewEmailAddress
     * @todo   Implement testSaveNewEmailAddress().
     */
    public function testSaveNewEmailAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::getUserIdByUsername
     * @todo   Implement testGetUserIdByUsername().
     */
    public function testGetUserIdByUsername() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::getUserDataByUsername
     * @todo   Implement testGetUserDataByUsername().
     */
    public function testGetUserDataByUsername() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers UserModel::getUserDataByUserIdAndToken
     * @todo   Implement testGetUserDataByUserIdAndToken().
     */
    public function testGetUserDataByUserIdAndToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
